name: Deploy all services to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Clone or update the repo
            if [ ! -d ~/multi-service-app ]; then
              git clone https://github.com/${{ github.repository }} ~/multi-service-app
            fi
            cd ~/multi-service-app
            git pull origin main

            # =======================
            # Deploy BACKEND
            # =======================
            docker stop bun-backend || true
            docker rm bun-backend || true
            docker build -t bun-backend -f docker/Dockerfile.backend .
            docker run -d -p 8080:8080 --name bun-backend bun-backend

            # =======================
            # Deploy FRONTEND
            # =======================
            docker stop bun-frontend || true
            docker rm bun-frontend || true
            docker build -t bun-frontend -f docker/Dockerfile.frontend .
            docker run -d -p 3000:3000 --name bun-frontend bun-frontend

            # =======================
            # Deploy WEBSOCKET
            # =======================
            docker stop bun-websocket || true
            docker rm bun-websocket || true
            docker build -t bun-websocket -f docker/Dockerfile.ws .
            docker run -d -p 4000:4000 --name bun-websocket bun-websocket
